In [1]:
import polars as pl

In [ ]:
schema = {
    "user_id": pl.String,
    "item_id": pl.String,
    "rating": pl.Float64,
    "timestamp": pl.Float64
}

df = pl.read_csv(
    "Amazon_All_Beauty.inter",
    separator="\t",
    new_columns=list(schema.keys()),
    schema=schema
)

In [22]:
df.height

693929

In [27]:
df = df.filter(pl.col("rating") >= 4)

df.height

494769

In [28]:
df.describe()

shape: (9, 5)
┌────────────┬──────────────────────────────┬────────────┬──────────┬───────────┐
│ statistic  ┆ user_id                      ┆ item_id    ┆ rating   ┆ timestamp │
│ ---        ┆ ---                          ┆ ---        ┆ ---      ┆ ---       │
│ str        ┆ str                          ┆ str        ┆ f64      ┆ f64       │
╞════════════╪══════════════════════════════╪════════════╪══════════╪═══════════╡
│ count      ┆ 494769                       ┆ 494769     ┆ 494769.0 ┆ 494769.0  │
│ null_count ┆ 0                            ┆ 0          ┆ 0.0      ┆ 0.0       │
│ mean       ┆ null                         ┆ null       ┆ 4.84118  ┆ 1.5512e12 │
│ std        ┆ null                         ┆ null       ┆ 0.365508 ┆ 8.0765e10 │
│ min        ┆ AE222BBOVZIF42YOOPNBXL4UUMYA ┆ 0005946468 ┆ 4.0      ┆ 9.7305e11 │
│ 25%        ┆ null                         ┆ null       ┆ 5.0      ┆ 1.4962e12 │
│ 50%        ┆ null                         ┆ null       ┆ 5.0      ┆ 1.5673e12 │
│ 75%        ┆ null                         ┆ null       ┆ 5.0      ┆ 1.6116e12 │
│ max        ┆ AHZZZSOTVOVACVK2WWXL4ITEAPIA ┆ B0CHXWTSM6 ┆ 5.0      ┆ 1.6942e12 │
└────────────┴──────────────────────────────┴────────────┴──────────┴───────────┘

In [31]:
df["user_id"].shape, df["user_id"].unique().shape

((494769,), (455579,))

In [33]:
df.group_by("user_id").agg(pl.count()).describe()

/var/folders/yz/m168t7js0w77j1c99gwrdglm0000gn/T/ipykernel_18090/3654098528.py:1: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  df.group_by("user_id").agg(pl.count()).describe()

shape: (9, 3)
┌────────────┬──────────────────────────────┬──────────┐
│ statistic  ┆ user_id                      ┆ count    │
│ ---        ┆ ---                          ┆ ---      │
│ str        ┆ str                          ┆ f64      │
╞════════════╪══════════════════════════════╪══════════╡
│ count      ┆ 455579                       ┆ 455579.0 │
│ null_count ┆ 0                            ┆ 0.0      │
│ mean       ┆ null                         ┆ 1.086022 │
│ std        ┆ null                         ┆ 0.699328 │
│ min        ┆ AE222BBOVZIF42YOOPNBXL4UUMYA ┆ 1.0      │
│ 25%        ┆ null                         ┆ 1.0      │
│ 50%        ┆ null                         ┆ 1.0      │
│ 75%        ┆ null                         ┆ 1.0      │
│ max        ┆ AHZZZSOTVOVACVK2WWXL4ITEAPIA ┆ 156.0    │
└────────────┴──────────────────────────────┴──────────┘

In [35]:
df = pl.read_ndjson(
    "All_Beauty.jsonl",
)

In [ ]:
df.filter(pl.col("rating") >= 4).height

500107

In [38]:
df["user_id"].shape, df["user_id"].unique().shape

((701528,), (631986,))

In [39]:
df.group_by("user_id").agg(pl.count()).describe()

/var/folders/yz/m168t7js0w77j1c99gwrdglm0000gn/T/ipykernel_18090/3654098528.py:1: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  df.group_by("user_id").agg(pl.count()).describe()

shape: (9, 3)
┌────────────┬──────────────────────────────┬──────────┐
│ statistic  ┆ user_id                      ┆ count    │
│ ---        ┆ ---                          ┆ ---      │
│ str        ┆ str                          ┆ f64      │
╞════════════╪══════════════════════════════╪══════════╡
│ count      ┆ 631986                       ┆ 631986.0 │
│ null_count ┆ 0                            ┆ 0.0      │
│ mean       ┆ null                         ┆ 1.110037 │
│ std        ┆ null                         ┆ 0.753202 │
│ min        ┆ AE222BBOVZIF42YOOPNBXL4UUMYA ┆ 1.0      │
│ 25%        ┆ null                         ┆ 1.0      │
│ 50%        ┆ null                         ┆ 1.0      │
│ 75%        ┆ null                         ┆ 1.0      │
│ max        ┆ AHZZZSOTVOVACVK2WWXL4ITEAPIA ┆ 165.0    │
└────────────┴──────────────────────────────┴──────────┘

In [72]:
from datasets import load_dataset

url = ("https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/"
       "resolve/main/raw/review_categories/All_Beauty.jsonl")
ds = load_dataset("json", data_files=url)

In [80]:
df = pl.from_pandas(ds['train'].to_pandas())

df.height, df["user_id"].shape, df["user_id"].unique().shape

(701528, (701528,), (631986,))

In [ ]:
df = df.with_columns([
    pl.col("asin").alias("item_id")
]).drop([   
    "asin",
    "helpful_vote",
    "title",
    "images",
    "text",
    "parent_asin",
    "verified_purchase",
])

In [76]:
df.group_by("user_id").agg(pl.count()).describe()

/var/folders/yz/m168t7js0w77j1c99gwrdglm0000gn/T/ipykernel_18090/3654098528.py:1: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  df.group_by("user_id").agg(pl.count()).describe()

shape: (9, 3)
┌────────────┬──────────────────────────────┬──────────┐
│ statistic  ┆ user_id                      ┆ count    │
│ ---        ┆ ---                          ┆ ---      │
│ str        ┆ str                          ┆ f64      │
╞════════════╪══════════════════════════════╪══════════╡
│ count      ┆ 631986                       ┆ 631986.0 │
│ null_count ┆ 0                            ┆ 0.0      │
│ mean       ┆ null                         ┆ 1.110037 │
│ std        ┆ null                         ┆ 0.753202 │
│ min        ┆ AE222BBOVZIF42YOOPNBXL4UUMYA ┆ 1.0      │
│ 25%        ┆ null                         ┆ 1.0      │
│ 50%        ┆ null                         ┆ 1.0      │
│ 75%        ┆ null                         ┆ 1.0      │
│ max        ┆ AHZZZSOTVOVACVK2WWXL4ITEAPIA ┆ 165.0    │
└────────────┴──────────────────────────────┴──────────┘

In [ ]:
from huggingface_hub import hf_hub_download

local_path = hf_hub_download(
    repo_id="McAuley-Lab/Amazon-Reviews-2023",
    filename="raw/review_categories/Beauty_and_Personal_Care.jsonl",
    repo_type="dataset"
)

df = pl.read_ndjson(local_path)

raw/review_categories/Beauty_and_Persona(…):   0%|          | 0.00/11.0G [00:00<?, ?B/s]

In [98]:
df.height

701528